# This file should NOT be changed.
# The application will not deploy correctly if this file is changed.
name: build-and-test

on:
  pull_request:
    branches: [main]
  release:
    types: [published]

jobs:
  build-and-test:

    runs-on: [self-hosted, linux, x64]

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Release soundness checks
      run: |
        now="$(date +'%Y.%m.%d.%H.%M')"
        if [[ $now < "${{ vars.SPRINT_BEGIN }}" || "${{ vars.SPRINT_END }}" < $now ]]; then
          echo "Releases can not be deployed outside of the sprint dates."
          echo "Sprint begin date:      ${{ vars.SPRINT_BEGIN }}"
          echo "Sprint end date:        ${{ vars.SPRINT_END }}"
          echo "Attempted release date: $now"
          exit 1
        fi
        if [[ ! ${{ github.ref_name }} =~ ^v([1-5]).(0|[1-9][0-9]*)$ ]]; then
          echo "Release tag not in expected format. (vX.X)"
          echo "In your tag, the major version should be your sprint number and the minor version should be 0 or another integer without leading zeros."
          exit 1
        fi
      if: github.event_name == 'release'
    
    - name: Pull request soundness checks
      run: |
        if [[ ! ${{ github.ref_name }} =~ ^([0-9]+)/merge$ ]]; then
          echo "Your pull was submitted before a runner could be assigned to it."
          echo "Do not merge before your code is tested on our servers."
          exit 1
        fi
      if: github.event_name != 'release'

    - name: Prepare for checkout # Avoids broken submodule self-hosted runner bug on checkout v2
      run: |
        git checkout -f $(git -c user.name="CS314 Runner" -c user.email="cs314@colostate.edu" commit-tree $(git hash-object -t tree /dev/null) < /dev/null) || :

    - uses: actions/checkout@v2

    - name: Prevent submodules from being added
      run: |
        echo "Submodules are not allowed in this repository. If a failure occurs on this step, please remove the submodule."
        substatus=$(git submodule status)
        if [[ $substatus != "" ]]; then
          printf "Submodule status: $substatus\n"
          exit 1
        fi

    - name: Set up node.js (${{ matrix.node-version }})
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Set up java (jdk-11)
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Install client dependencies
      run: cache_dependencies client

    - name: Install server dependencies
      run: cache_dependencies server

    - name: Prepare Codeclimate reporting tools
      env:
        GIT_BRANCH: ${{ github.head_ref }}
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
        ./cc-test-reporter before-build

    - name: Run client tests
      run: npm test --prefix client
      
    - name: Bundle client with webpack
      run: npm run prodClient --prefix client
      
    - name: Build & test server with maven
      run: mvn -f server --global-settings server/.m2/settings.xml verify

    - name: Postman tests
      env:
        DEV_PORT_BASE: ${{ vars.DEV_PORT_BASE }}
        DEV_PORT_BLOCK_SIZE: ${{ vars.DEV_PORT_BLOCK_SIZE }}
      run: postman
 
    - name: Deploy server
      env:
        GITHUB_USER: ${{ github.actor }}
        DEV_PORT_BASE: ${{ vars.DEV_PORT_BASE }}
        DEV_PORT_BLOCK_SIZE: ${{ vars.DEV_PORT_BLOCK_SIZE }}
      run: build-test-deploy

    - name: Finish and report Codeclimate statistics
      env:
        GIT_BRANCH: ${{ github.head_ref }}
        JACOCO_SOURCE_PATH: server/src/main/java
      run: |
        ./cc-test-reporter format-coverage -t jacoco target/site/jacoco/jacoco.xml --output "codeclimate.java.json"
        ./cc-test-reporter format-coverage -t clover target/coverage/client/clover.xml --output "codeclimate.js.json"
        ./cc-test-reporter sum-coverage --output "codeclimate.combined.json" codeclimate.*.json
        ./cc-test-reporter upload-coverage --input "codeclimate.combined.json"
